# Generated by Django 5.0.4 on 2024-04-18 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='type',
            new_name='vehicle_type',
        ),
    ]
