# Generated by Django 5.0.4 on 2024-04-22 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_rename_type_car_vehicle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ATACQ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle', to='demoapp.car')),
            ],
        ),
    ]
