# Generated by Django 5.0.4 on 2024-05-07 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='type',
        ),
        migrations.AddField(
            model_name='car',
            name='ATACQ_Item',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='car',
            name='Rfid',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ATACQ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle', to='demoapp.car')),
            ],
        ),
    ]
