# Generated by Django 5.0.7 on 2024-08-01 19:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("demoapp", "0003_react_remove_vehicle_atacq_delete_car_delete_vehicle"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="React",
            new_name="User",
        ),
    ]
